<a href="https://colab.research.google.com/github/RajeshRanaGiet/IML-Lab/blob/main/Experiment-2/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a1 = np.array([1,2,3,4,5,6])
print(a1)

[1 2 3 4 5 6]


In [ ]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.sum(a1))
print(np.multiply(a1,a2))
print(np.exp(a1))

6
[ 4 10 18]
[ 2.71828183  7.3890561  20.08553692]


In [ ]:
a1 = np.array([1,2,3,4,5,6])
print("First element is ", a1[0])
print("Last element is ", a1[-1])
print("From 2 to 4 element is ", a1[2:5])

First element is  1
Last element is  6
From 2 to 4 element is  [3 4 5]


In [ ]:
import numpy as np

a1 = np.array([[1, 2, 3],[4, 5, 6]])

a2 = np.array([[1, 2],[3, 4],[5, 6]])

a3 = np.zeros((2, 2))

for i in range(2):
    for j in range(2):
        for k in range(3):
            a3[i][j] += a1[i][k] * a2[k][j]

print(a3)


[[22. 28.]
 [49. 64.]]


In [ ]:
a1 = [1,2,3,4,5,6]
print('Maximum is', np.max(a1))
print("Mininmum is", np.min(a1))
print("Average maximum is", np.argmax(a1))
print("Average minimum is", np.argmin(a1))

Maximum is  6


In [ ]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
print(np.concatenate((a1, a2)))
print(np.stack((a1, a2)))
print(np.vstack((a1, a2)))


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
print("Element wise equal", a1 == a2)
print("Element wise greater", a1 > a2)
print("Element wise less", a1 < a2)

Element wise equal [False False False]
Element wise greater [False False False]
Element wise less [ True  True  True]


In [47]:
try:
  raw_x = input("Enter x values separated by space: ")
  raw_y = input("Enter y values separated by space: ")

  x = [float(i) for i in raw_x.split()]
  y = [float(i) for i in raw_y.split()]

  n = len(x)

  if n != len(y):
    print("Error: The number of X and Y values must be the same.")
  elif n < 2:
    print("Error: You need at least two points to form a line.")
  else:
    sum_x = sum(x)
    sum_y = sum(y)
    sum_xy = sum([x[i] * y[i] for i in range(n)])
    sum_x_sq = sum([x[i] ** 2 for i in range(n)])

    numerator_m = (n * sum_xy) - (sum_x * sum_y)
    denominator_m = (n * sum_x_sq) - (sum_x ** 2)

    if denominator_m == 0:
      print("Error: Vertical line detected (denominator is zero).")
    else:
      m = numerator_m / denominator_m

      c = (sum_y - (m * sum_x)) / n

      print("\n" + "-"*30)
      print(f"Slope (m):     {m:.4f}")
      print(f"Intercept (c): {c:.4f}")
      print(f"Equation:      y = {m:.4f}x + {c:.4f}")
      print("-"*30)

except ValueError:
    print("Error: Please enter only numbers separated by spaces.")



Enter x values separated by space: 12 13 14 15 16 17
Enter y values separated by space: 2 3 4 5 6 7

------------------------------
Slope (m):     1.0000
Intercept (c): -10.0000
Equation:      y = 1.0000x + -10.0000
------------------------------


In [50]:
import numpy as np
from scipy import stats

try:
  raw_x = input("Enter x values separated by space: ")
  raw_y = input("Enter y values separated by space: ")

  x = np.array([float(i) for i in raw_x.split()])
  y = np.array([float(i) for i in raw_y.split()])

  slope, intercept, _, _, _ = stats.stats.linregress(x,y)

  print("\n" + "-"*30)
  print(f"Slope (m):     {m:.4f}")
  print(f"Intercept (c): {c:.4f}")
  print(f"Equation:      y = {slope:.4f}x + {intercept:.4f}")
  print("-"*30)

except ValueError:
  print("Error: Please enter only numbers separated by spaces.")
except Exception as e:
  print(f"An error occurred: {e}")

Enter x values separated by space: 1 2 3 4 5 6
Enter y values separated by space: 12 13 14 15 16 17

------------------------------
Slope (m):     1.0000
Intercept (c): -10.0000
Equation:      y = 1.0000x + 11.0000
------------------------------


/tmp/ipython-input-2873590272.py:11: DeprecationWarning: Please import `linregress` from the `scipy.stats` namespace; the `scipy.stats.stats` namespace is deprecated and will be removed in SciPy 2.0.0.
  slope, intercept, _, _, _ = stats.stats.linregress(x,y)
